FROM maven:3.8.3-openjdk-17 AS build
COPY ./ /app
WORKDIR /app
RUN microdnf install -y libatomic && \
    mvn --show-version --update-snapshots --batch-mode clean package

FROM eclipse-temurin:17-jre
RUN mkdir /app
WORKDIR /app
COPY --from=build ./app/api/target/ape-messaging-api-1.0.0-SNAPSHOT.jar /app
EXPOSE 8080
CMD ["java", "-jar", "ape-messaging-api-1.0.0-SNAPSHOT.jar"]
